### ISSUE TITLE
Cannot import experiment_function in Python 3.7.1

### ISSUE THREAD

**Issue by NomelemoN** [QUVA-Lab/artemis#141]
Hi,

I am trying to use the framework in Python 3.7.1. in Anaconda3 on Windows 10. However, upon attempting to import the experiment_function, I get the following error:

```
Installing collected packages: artemis-ml
Successfully installed artemis-ml-2.0.0

(MasterThesisCode) C:\WINDOWS\system32>python
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from artemis.experiments import experiment_function
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\fileman\config_files.py", line 56, in get_config_value
    value = config.get(section, option)
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'fileman'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\experiments\__init__.py", line 1, in <module>
    from artemis.experiments.decorators import experiment_function, experiment_root, ExperimentFunction
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\experiments\decorators.py", line 3, in <module>
    from artemis.experiments.experiment_record_view import show_record, compare_experiment_records
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\experiments\experiment_record_view.py", line 5, in <module>
    from artemis.experiments.experiment_management import load_lastest_experiment_results
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\experiments\experiment_management.py", line 14, in <module>
    from artemis.general.display import equalize_string_lengths
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\general\display.py", line 7, in <module>
    from artemis.fileman.local_dir import make_file_dir
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\fileman\local_dir.py", line 24, in <module>
    LOCAL_DIR = get_artemis_config_value(section='fileman', option='data_dir', default_generator = get_default_local_path, write_default = True)
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\config.py", line 32, in get_artemis_config_value
    return get_config_value(config_filename, section=section, option=option, default_generator=default_generator, write_default=write_default, read_method=read_method)
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\fileman\config_files.py", line 61, in get_config_value
    value = default_generator() if callable(default_generator) else default_generator
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\site-packages\artemis\fileman\local_dir.py", line 22, in get_default_local_path
    return os.path.join(os.getenv("HOME"), '.artemis')
  File "C:\ProgramData\Anaconda3\envs\MasterThesisCode\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The command 
```
python -m artemis.plotting.demo_dbplot
```
does yield the expected result however.

**Comment by petered** [comment]
Thanks @NomelemoN, looking into it now
