### ISSUE TITLE
Menu crash in browse_experiments()

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#28]
Reproducible by:
browse_experiments() -> records -> "Enter" (no text input), leads to:
```
Enter Command (show # to show and experiment, or h for help) >>
Traceback (most recent call last):
  File "distributed_vi/SGD_experiments/convergence_experiments.py", line 273, in <module>
    browse_experiments()
  File "/home/mreisser/virtualenvs/tensorflow4/src/artemis/artemis/experiments/ui.py", line 90, in browse_experiments
    browse_experiment_records()
  File "/home/mreisser/virtualenvs/tensorflow4/src/artemis/artemis/experiments/ui.py", line 155, in browse_experiment_records
    cmd = parts[0]
IndexError: list index out of range
```

**Comment by petered** [comment]
Resolved in https://github.com/QUVA-Lab/artemis/pull/29
