### ISSUE TITLE
Installation requires plato

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#3]
pip install -e git+http://github.com/QUVA-Lab/artemis.git#egg=artemis 
fails because it tries to import plato

**Comment by matthiasreisser** [comment]
@petered

**Comment by matthiasreisser** [comment]
Error-message:
Obtaining artemis from git+http://github.com/QUVA-Lab/artemis.git#egg=artemis
  Cloning http://github.com/QUVA-Lab/artemis.git to ./virtualenvs/TensorFlow2/src/artemis
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/matthias/virtualenvs/TensorFlow2/src/artemis/setup.py", line 4, in <module>
        import plato
    ImportError: No module named plato
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/matthias/virtualenvs/TensorFlow2/src/artemis/


Is this solved by simply removing the import from setup.py?
