### ISSUE TITLE
Some strange issue

### ISSUE THREAD

**Issue by matthiasreisser** [QUVA-Lab/artemis#78]
```
WARNING:root:Could not import scipy.weave.  That's ok, ignore this unless you need it.
==================== Experiments ====================
Traceback (most recent call last):
  File "MSGLD/experiments/regression_posterior_experiment.py", line 197, in <module>
    regression_sampler.browse()
  File "/home/mreisser/PycharmProjects/artemis/artemis/experiments/experiments.py", line 236, in browse
    browse_experiments(root_experiment=self, **kwargs)
  File "/home/mreisser/PycharmProjects/artemis/artemis/experiments/ui.py", line 40, in browse_experiments
    browser.launch(command=command)
  File "/home/mreisser/PycharmProjects/artemis/artemis/experiments/ui.py", line 182, in launch
    print self.get_experiment_list_str(self.exp_record_dict, just_last_record=self.just_last_record, view_mode=self.view_mode, raise_display_errors=self.raise_display_errors, truncate_result_to=self.truncate_result_to)
  File "/home/mreisser/PycharmProjects/artemis/artemis/experiments/ui.py", line 265, in get_experiment_list_str
    table = tabulate(rows, headers=headers)
  File "/home/mreisser/virtualenvs/msgld/local/lib/python2.7/site-packages/tabulate.py", line 1119, in tabulate
    ['\t'.join(map(_text_type, row)) for row in list_of_lists])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)
```

List of experiments in folder at the time of execution:
![image](https://user-images.githubusercontent.com/8858505/29608642-0d1dff06-87f5-11e7-952c-ee793121ffad.png)

of which only the last one was supposed to be loaded...

**Comment by petered** [comment]
Addressed in https://github.com/QUVA-Lab/artemis/pull/81, but I can't know if it works until you can reproduce the errror.  Lets leave this issue (and pull) open until the error comes back.

**Comment by petered** [comment]
Yeah so it's fixed in the peter branch.  It'll be merged in soon.
